version: '3'

networks:
  proxy-tier:
    external:
      name: nginx-proxy

services:
  omnikanji:
    build: .
    environment:
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
    networks:
      - proxy-tier

